package com.nit.Exception;

public class InnerTryProject {
    public static void main(String[] args) {
        Division01.div();
    }
}
